services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV:-local}
      STORAGE_DIR: "/app/data"
      PORT: ${PORT}
      DB_HOST: "db"
      DB_PORT: ${DB_PORT}
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?search_path=${DB_SCHEMA}&sslmode=disable"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      CERTIFICATE_PUBLIC_KEY: ${CERTIFICATE_PUBLIC_KEY}
      CERTIFICATE_PRIVATE_KEY: ${CERTIFICATE_PRIVATE_KEY}
      ADMIN_ENDPOINT_ENABLED: ${ADMIN_ENDPOINT_ENABLED}
      ADMIN_ENDPOINT_KEY: ${ADMIN_ENDPOINT_KEY}
    volumes:
        - jasper_storage_data:/app/data
        - ./certs:/app/certs:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jasper_network

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - jasper_db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - jasper_network

volumes:
  jasper_db_data:
  jasper_storage_data:
networks:
  jasper_network:
