services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      STORAGE_DIR: ${STORAGE_DIR}
      PORT: ${PORT}
      JASPER_DB_HOST: ${JASPER_DB_HOST}
      JASPER_DB_PORT: ${JASPER_DB_PORT}
      JASPER_DB_DATABASE: ${JASPER_DB_DATABASE}
      JASPER_DB_USERNAME: ${JASPER_DB_USERNAME}
      JASPER_DB_PASSWORD: ${JASPER_DB_PASSWORD}
      JASPER_DB_SCHEMA: ${JASPER_DB_SCHEMA}
      CERTIFICATE_PUBLIC_KEY: ${CERTIFICATE_PUBLIC_KEY}
      CERTIFICATE_PRIVATE_KEY: ${CERTIFICATE_PRIVATE_KEY}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      psql_bp:
        condition: service_healthy
    networks:
      - jasper
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${JASPER_DB_DATABASE}
      POSTGRES_USER: ${JASPER_DB_USERNAME}
      POSTGRES_PASSWORD: ${JASPER_DB_PASSWORD}
    ports:
      - "${JASPER_DB_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${JASPER_DB_USERNAME} -d ${JASPER_DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - jasper

volumes:
  psql_volume_bp:
networks:
  jasper:
